"""Bluetooth LE SMP constants
"""
OOB_DISABLED = 0x00
OOB_ENABLED = 0x01

IOCAP_DISPLAY_ONLY = 0x00
IOCAP_DISPLAY_YESNO = 0x01
IOCAP_KEYBD_ONLY = 0x02
IOCAP_NOINPUT_NOOUTPUT = 0x03
IOCAP_KEYBD_DISPLAY = 0x04

PM_LEGACY_JUSTWORKS = 0x00
PM_LEGACY_PASSKEY = 0x01
PM_OOB = 0x02
PM_LESC_JUSTWORKS = 0x03
PM_LESC_NUMCOMP = 0x04
PM_LESC_OOB = 0x05

SM_ERROR_PASSKEY_ENTRY_FAILED = 0x01
SM_ERROR_OOB_NOT_AVAIL = 0x02
SM_ERROR_AUTH_REQ = 0x03
SM_ERROR_CONFIRM_VALUE_FAILED = 0x04
SM_ERROR_UNSUPP_PAIRING = 0x05
SM_ERROR_ENC_KEY_SIZE = 0x06
SM_ERROR_UNSUPP_COMMAND = 0x07
SM_ERROR_UNSPEC_REASON = 0x08
SM_ERROR_REPEATED_ATTEMPTS = 0x09
SM_ERROR_INVALID_PARAMS = 0x0A
SM_ERROR_DHKEY_CHECK_FAILED = 0x0B
SM_ERROR_NUMCOMP_FAILED = 0x0C
SM_ERROR_BREDR_PAIRING = 0x0D
SM_ERROR_CROSS_TRANSP_NOT_ALLOWED = 0x0E
SM_ERROR_KEY_REJECTED = 0x0F