# ARBITRARY, ONLY FOR INTERNAL USE IN WHAD
VIRTUAL_ADDR_TYPE = 0x00
GROUP_ADDR_TYPE = 0x01
UNICAST_ADDR_TYPE = 0x02
UNASSIGNED_ADDR_TYPE = 0x03


# CREDENTIALS FOR THE NETWORK LAYER
MANAGED_FLOODING_CREDS = 0x00
FRIEND_CREDS = 0x01
DIRECTED_FORWARDING_CREDS = 0x02
