# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/generic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protocol/generic.proto\x12\x07generic\"0\n\tCmdResult\x12#\n\x06result\x18\x01 \x01(\x0e\x32\x13.generic.ResultCode\"\x19\n\x08Progress\x12\r\n\x05value\x18\x01 \x01(\r\"\'\n\x08\x44\x65\x62ugMsg\x12\r\n\x05level\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1a\n\nVerboseMsg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xd4\x01\n\x07Message\x12%\n\x06result\x18\x01 \x01(\x0e\x32\x13.generic.ResultCodeH\x00\x12(\n\ncmd_result\x18\x02 \x01(\x0b\x32\x12.generic.CmdResultH\x00\x12%\n\x08progress\x18\x03 \x01(\x0b\x32\x11.generic.ProgressH\x00\x12\"\n\x05\x64\x65\x62ug\x18\x04 \x01(\x0b\x32\x11.generic.DebugMsgH\x00\x12&\n\x07verbose\x18\x05 \x01(\x0b\x32\x13.generic.VerboseMsgH\x00\x42\x05\n\x03msg*}\n\nResultCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x13\n\x0fPARAMETER_ERROR\x10\x02\x12\x10\n\x0c\x44ISCONNECTED\x10\x03\x12\x0e\n\nWRONG_MODE\x10\x04\x12\x16\n\x12UNSUPPORTED_DOMAIN\x10\x05\x12\x08\n\x04\x42USY\x10\x06\x62\x06proto3')

_RESULTCODE = DESCRIPTOR.enum_types_by_name['ResultCode']
ResultCode = enum_type_wrapper.EnumTypeWrapper(_RESULTCODE)
SUCCESS = 0
ERROR = 1
PARAMETER_ERROR = 2
DISCONNECTED = 3
WRONG_MODE = 4
UNSUPPORTED_DOMAIN = 5
BUSY = 6


_CMDRESULT = DESCRIPTOR.message_types_by_name['CmdResult']
_PROGRESS = DESCRIPTOR.message_types_by_name['Progress']
_DEBUGMSG = DESCRIPTOR.message_types_by_name['DebugMsg']
_VERBOSEMSG = DESCRIPTOR.message_types_by_name['VerboseMsg']
_MESSAGE = DESCRIPTOR.message_types_by_name['Message']
CmdResult = _reflection.GeneratedProtocolMessageType('CmdResult', (_message.Message,), {
  'DESCRIPTOR' : _CMDRESULT,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.CmdResult)
  })
_sym_db.RegisterMessage(CmdResult)

Progress = _reflection.GeneratedProtocolMessageType('Progress', (_message.Message,), {
  'DESCRIPTOR' : _PROGRESS,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.Progress)
  })
_sym_db.RegisterMessage(Progress)

DebugMsg = _reflection.GeneratedProtocolMessageType('DebugMsg', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGMSG,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.DebugMsg)
  })
_sym_db.RegisterMessage(DebugMsg)

VerboseMsg = _reflection.GeneratedProtocolMessageType('VerboseMsg', (_message.Message,), {
  'DESCRIPTOR' : _VERBOSEMSG,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.VerboseMsg)
  })
_sym_db.RegisterMessage(VerboseMsg)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.Message)
  })
_sym_db.RegisterMessage(Message)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _RESULTCODE._serialized_start=396
  _RESULTCODE._serialized_end=521
  _CMDRESULT._serialized_start=35
  _CMDRESULT._serialized_end=83
  _PROGRESS._serialized_start=85
  _PROGRESS._serialized_end=110
  _DEBUGMSG._serialized_start=112
  _DEBUGMSG._serialized_end=151
  _VERBOSEMSG._serialized_start=153
  _VERBOSEMSG._serialized_end=179
  _MESSAGE._serialized_start=182
  _MESSAGE._serialized_end=394
# @@protoc_insertion_point(module_scope)
