# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/generic.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol/generic.proto',
  package='generic',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16protocol/generic.proto\x12\x07generic\"0\n\tCmdResult\x12#\n\x06result\x18\x01 \x01(\x0e\x32\x13.generic.ResultCode\"\x19\n\x08Progress\x12\r\n\x05value\x18\x01 \x01(\r\"\'\n\x08\x44\x65\x62ugMsg\x12\r\n\x05level\x18\x01 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x1a\n\nVerboseMsg\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xd4\x01\n\x07Message\x12%\n\x06result\x18\x01 \x01(\x0e\x32\x13.generic.ResultCodeH\x00\x12(\n\ncmd_result\x18\x02 \x01(\x0b\x32\x12.generic.CmdResultH\x00\x12%\n\x08progress\x18\x03 \x01(\x0b\x32\x11.generic.ProgressH\x00\x12\"\n\x05\x64\x65\x62ug\x18\x04 \x01(\x0b\x32\x11.generic.DebugMsgH\x00\x12&\n\x07verbose\x18\x05 \x01(\x0b\x32\x13.generic.VerboseMsgH\x00\x42\x05\n\x03msg*s\n\nResultCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x12\x13\n\x0fPARAMETER_ERROR\x10\x02\x12\x10\n\x0c\x44ISCONNECTED\x10\x03\x12\x0e\n\nWRONG_MODE\x10\x04\x12\x16\n\x12UNSUPPORTED_DOMAIN\x10\x05\x62\x06proto3'
)

_RESULTCODE = _descriptor.EnumDescriptor(
  name='ResultCode',
  full_name='generic.ResultCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PARAMETER_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='DISCONNECTED', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WRONG_MODE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNSUPPORTED_DOMAIN', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=396,
  serialized_end=511,
)
_sym_db.RegisterEnumDescriptor(_RESULTCODE)

ResultCode = enum_type_wrapper.EnumTypeWrapper(_RESULTCODE)
SUCCESS = 0
ERROR = 1
PARAMETER_ERROR = 2
DISCONNECTED = 3
WRONG_MODE = 4
UNSUPPORTED_DOMAIN = 5



_CMDRESULT = _descriptor.Descriptor(
  name='CmdResult',
  full_name='generic.CmdResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='generic.CmdResult.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=83,
)


_PROGRESS = _descriptor.Descriptor(
  name='Progress',
  full_name='generic.Progress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='generic.Progress.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=110,
)


_DEBUGMSG = _descriptor.Descriptor(
  name='DebugMsg',
  full_name='generic.DebugMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='generic.DebugMsg.level', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='generic.DebugMsg.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=151,
)


_VERBOSEMSG = _descriptor.Descriptor(
  name='VerboseMsg',
  full_name='generic.VerboseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='generic.VerboseMsg.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=179,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='generic.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='generic.Message.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cmd_result', full_name='generic.Message.cmd_result', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='progress', full_name='generic.Message.progress', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='debug', full_name='generic.Message.debug', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='generic.Message.verbose', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='generic.Message.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=182,
  serialized_end=394,
)

_CMDRESULT.fields_by_name['result'].enum_type = _RESULTCODE
_MESSAGE.fields_by_name['result'].enum_type = _RESULTCODE
_MESSAGE.fields_by_name['cmd_result'].message_type = _CMDRESULT
_MESSAGE.fields_by_name['progress'].message_type = _PROGRESS
_MESSAGE.fields_by_name['debug'].message_type = _DEBUGMSG
_MESSAGE.fields_by_name['verbose'].message_type = _VERBOSEMSG
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['result'])
_MESSAGE.fields_by_name['result'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['cmd_result'])
_MESSAGE.fields_by_name['cmd_result'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['progress'])
_MESSAGE.fields_by_name['progress'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['debug'])
_MESSAGE.fields_by_name['debug'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
_MESSAGE.oneofs_by_name['msg'].fields.append(
  _MESSAGE.fields_by_name['verbose'])
_MESSAGE.fields_by_name['verbose'].containing_oneof = _MESSAGE.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['CmdResult'] = _CMDRESULT
DESCRIPTOR.message_types_by_name['Progress'] = _PROGRESS
DESCRIPTOR.message_types_by_name['DebugMsg'] = _DEBUGMSG
DESCRIPTOR.message_types_by_name['VerboseMsg'] = _VERBOSEMSG
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.enum_types_by_name['ResultCode'] = _RESULTCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CmdResult = _reflection.GeneratedProtocolMessageType('CmdResult', (_message.Message,), {
  'DESCRIPTOR' : _CMDRESULT,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.CmdResult)
  })
_sym_db.RegisterMessage(CmdResult)

Progress = _reflection.GeneratedProtocolMessageType('Progress', (_message.Message,), {
  'DESCRIPTOR' : _PROGRESS,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.Progress)
  })
_sym_db.RegisterMessage(Progress)

DebugMsg = _reflection.GeneratedProtocolMessageType('DebugMsg', (_message.Message,), {
  'DESCRIPTOR' : _DEBUGMSG,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.DebugMsg)
  })
_sym_db.RegisterMessage(DebugMsg)

VerboseMsg = _reflection.GeneratedProtocolMessageType('VerboseMsg', (_message.Message,), {
  'DESCRIPTOR' : _VERBOSEMSG,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.VerboseMsg)
  })
_sym_db.RegisterMessage(VerboseMsg)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'protocol.generic_pb2'
  # @@protoc_insertion_point(class_scope:generic.Message)
  })
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
