class AntStickIds:
    ANTSTICK_ID_VENDOR      = 0x0FCF
    ANTSTICK_ID_PRODUCT     = 0x1008
    ANTSTICK2_ID_PRODUCT    = 0x1009


class AntMessageCode:
    RESPONSE_NO_ERROR = 0
    EVENT_RX_SEARCH_TIMEOUT = 1
    EVENT_RX_FAIL = 2
    EVENT_TX = 3
    EVENT_TRANSFER_RX_FAILED = 4
    EVENT_TRANSFER_TX_COMPLETED = 5
    EVENT_TRANSFER_TX_FAILED = 6
    EVENT_CHANNEL_CLOSED = 7
    EVENT_RX_FAIL_TO_GO_TO_SEARCH = 8
    EVENT_CHANNEL_COLLISION = 9
    EVENT_TRANSFER_TX_START = 10
    EVENT_TRANSFER_NEXT_DATA_BLOCK = 17
    CHANNEL_IN_WRONG_STATE = 21
    CHANNEL_NOT_OPENED = 22
    CHANNEL_ID_NOT_SET = 24
    CLOSE_ALL_CHANNELS = 25
    TRANSFER_IN_PROGRESS = 31
    TRANSFER_SEQUENCE_NUMBER_ERROR = 32
    TRANSFER_IN_ERROR = 33
    MESSAGE_SIZE_EXCEEDS_LIMIT = 39
    INVALID_MESSAGE = 40
    INVALID_NETWORK_NUMBER = 41
    INVALID_LIST_ID = 48
    INVALID_SCAN_TX_CHANNEL = 49
    INVALID_PARAMETER_PROVIDED = 51
    INVALID_SERIAL_QUE_OVERFLOW = 52
    EVENT_QUE_OVERFLOW = 53
    ENCRYPT_NEGOTIATION_SUCCESS = 56
    ENCRYPT_NEGOTIATION_FAIL = 57
    NVM_FULL_ERROR = 64
    NVM_WRITE_ERROR = 65
    USB_STRING_WRITE_FAIL = 112
    MSG_SERIAL_ERROR_ID = 174

