# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whad/protocol/ble/ble.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()





_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'whad.protocol.ble.ble_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BLECOMMAND._serialized_start=6640
  _BLECOMMAND._serialized_end=7177
  _BLEADVTYPE._serialized_start=7180
  _BLEADVTYPE._serialized_end=7338
  _BLEDIRECTION._serialized_start=7340
  _BLEDIRECTION._serialized_end=7458
  _BLEADDRTYPE._serialized_start=7460
  _BLEADDRTYPE._serialized_end=7506
  _BLEPHY._serialized_start=7508
  _BLEPHY._serialized_end=7570
  _BLECSA._serialized_start=7572
  _BLECSA._serialized_end=7633
  _SETBDADDRESSCMD._serialized_start=36
  _SETBDADDRESSCMD._serialized_end=110
  _SNIFFADVCMD._serialized_start=112
  _SNIFFADVCMD._serialized_end=183
  _JAMADVCMD._serialized_start=185
  _JAMADVCMD._serialized_end=196
  _JAMADVONCHANNELCMD._serialized_start=198
  _JAMADVONCHANNELCMD._serialized_end=235
  _SNIFFCONNREQCMD._serialized_start=237
  _SNIFFCONNREQCMD._serialized_end=348
  _SNIFFACCESSADDRESSCMD._serialized_start=350
  _SNIFFACCESSADDRESSCMD._serialized_end=427
  _SNIFFACTIVECONNCMD._serialized_start=430
  _SNIFFACTIVECONNCMD._serialized_end=612
  _JAMCONNCMD._serialized_start=614
  _JAMCONNCMD._serialized_end=676
  _SCANMODECMD._serialized_start=678
  _SCANMODECMD._serialized_end=733
  _ADVMODECMD._serialized_start=736
  _ADVMODECMD._serialized_end=942
  _SETADVDATACMD._serialized_start=944
  _SETADVDATACMD._serialized_end=999
  _SETEXTADVPDUSCMD._serialized_start=1001
  _SETEXTADVPDUSCMD._serialized_end=1049
  _AUXPTR._serialized_start=1051
  _AUXPTR._serialized_end=1152
  _EXTADVPDU._serialized_start=1155
  _EXTADVPDU._serialized_end=1285
  _CENTRALMODECMD._serialized_start=1287
  _CENTRALMODECMD._serialized_end=1303
  _CONNECTTOCMD._serialized_start=1306
  _CONNECTTOCMD._serialized_end=1619
  _SENDRAWPDUCMD._serialized_start=1622
  _SENDRAWPDUCMD._serialized_end=1802
  _SENDPDUCMD._serialized_start=1805
  _SENDPDUCMD._serialized_end=1945
  _DISCONNECTCMD._serialized_start=1947
  _DISCONNECTCMD._serialized_end=1983
  _PERIPHERALMODECMD._serialized_start=1986
  _PERIPHERALMODECMD._serialized_end=2199
  _STARTCMD._serialized_start=2201
  _STARTCMD._serialized_end=2211
  _STOPCMD._serialized_start=2213
  _STOPCMD._serialized_end=2222
  _HIJACKMASTERCMD._serialized_start=2224
  _HIJACKMASTERCMD._serialized_end=2265
  _HIJACKSLAVECMD._serialized_start=2267
  _HIJACKSLAVECMD._serialized_end=2307
  _HIJACKBOTHCMD._serialized_start=2309
  _HIJACKBOTHCMD._serialized_end=2348
  _SETENCRYPTIONCMD._serialized_start=2351
  _SETENCRYPTIONCMD._serialized_end=2479
  _REACTIVEJAMCMD._serialized_start=2481
  _REACTIVEJAMCMD._serialized_end=2575
  _PREPARESEQUENCECMD._serialized_start=2578
  _PREPARESEQUENCECMD._serialized_end=3143
  _PREPARESEQUENCECMD_RECEPTIONTRIGGER._serialized_start=2757
  _PREPARESEQUENCECMD_RECEPTIONTRIGGER._serialized_end=2822
  _PREPARESEQUENCECMD_CONNECTIONEVENTTRIGGER._serialized_start=2824
  _PREPARESEQUENCECMD_CONNECTIONEVENTTRIGGER._serialized_end=2874
  _PREPARESEQUENCECMD_MANUALTRIGGER._serialized_start=2876
  _PREPARESEQUENCECMD_MANUALTRIGGER._serialized_end=2891
  _PREPARESEQUENCECMD_TRIGGER._serialized_start=2894
  _PREPARESEQUENCECMD_TRIGGER._serialized_end=3110
  _PREPARESEQUENCECMD_PENDINGPACKET._serialized_start=3112
  _PREPARESEQUENCECMD_PENDINGPACKET._serialized_end=3143
  _TRIGGERSEQUENCECMD._serialized_start=3145
  _TRIGGERSEQUENCECMD._serialized_end=3177
  _DELETESEQUENCECMD._serialized_start=3179
  _DELETESEQUENCECMD._serialized_end=3210
  _SETPHYCMD._serialized_start=3212
  _SETPHYCMD._serialized_end=3281
  _SETSUPPORTEDPHYSCMD._serialized_start=3283
  _SETSUPPORTEDPHYSCMD._serialized_end=3362
  _SETTXPOWERLEVELCMD._serialized_start=3364
  _SETTXPOWERLEVELCMD._serialized_end=3399
  _TRIGGERED._serialized_start=3401
  _TRIGGERED._serialized_end=3424
  _ACCESSADDRESSDISCOVERED._serialized_start=3426
  _ACCESSADDRESSDISCOVERED._serialized_end=3541
  _ADVPDURECEIVED._serialized_start=3544
  _ADVPDURECEIVED._serialized_end=3727
  _CONNECTED._serialized_start=3730
  _CONNECTED._serialized_end=3934
  _DISCONNECTED._serialized_start=3936
  _DISCONNECTED._serialized_end=3987
  _SYNCHRONIZED._serialized_start=3990
  _SYNCHRONIZED._serialized_end=4151
  _DESYNCHRONIZED._serialized_start=4153
  _DESYNCHRONIZED._serialized_end=4193
  _HIJACKED._serialized_start=4195
  _HIJACKED._serialized_end=4246
  _INJECTED._serialized_start=4248
  _INJECTED._serialized_end=4327
  _RAWPDURECEIVED._serialized_start=4330
  _RAWPDURECEIVED._serialized_end=4702
  _PDURECEIVED._serialized_start=4705
  _PDURECEIVED._serialized_end=4854
  _MESSAGE._serialized_start=4857
  _MESSAGE._serialized_end=6637
# @@protoc_insertion_point(module_scope)
