MODEL_ID_TO_NAME = {
    0: "Configuration Server",
    1: "Configuration Client",
    2: "Health Server",
    3: "Health Client",
    6: "Directed Forwarding Configuration Server",
    7: "Directed Forwarding Configuration Client",
    4: "Remote Provisioning Server",
    5: "Remote Provisioning Client",
    8: "Bridge Configuration Server",
    9: "Bridge Configuration Client",
    10: "Mesh Private Beacon Server",
    11: "Mesh Private Beacon Client",
    12: "On-Demand Private Proxy Server",
    13: "On-Demand Private Proxy Client",
    14: "SAR Configuration Server",
    15: "SAR Configuration Client",
    16: "Opcodes Aggregator Server",
    17: "Opcodes Aggregator Client",
    18: "Large Composition Data Server",
    19: "Large Composition Data Client",
    20: "Solicitation PDU RPL Configuration Server",
    21: "Solicitation PDU RPL Configuration Client",
    4096: "Generic OnOff Server",
    4097: "Generic OnOff Client",
    4098: "Generic Level Server",
    4099: "Generic Level Client",
    4100: "Generic Default Transition Time Server",
    4101: "Generic Default Transition Time Client",
    4102: "Generic Power OnOff Server",
    4103: "Generic Power OnOff Setup Server",
    4104: "Generic Power OnOff Client",
    4105: "Generic Power Level Server",
    4106: "Generic Power Level Setup Server",
    4107: "Generic Power Level Client",
    4108: "Generic Battery Server",
    4109: "Generic Battery Client",
    4110: "Generic Location Server",
    4111: "Generic Location Setup Server",
    4112: "Generic Location Client",
    4113: "Generic Admin Property Server",
    4114: "Generic Manufacturer Property Server",
    4115: "Generic User Property Server",
    4116: "Generic Client Property Server",
    4117: "Generic Property Client",
    4352: "Sensor Server",
    4353: "Sensor Setup Server",
    4354: "Sensor Client",
    4608: "Time Server",
    4609: "Time Setup Server",
    4610: "Time Client",
    4611: "Scene Server",
    4612: "Scene Setup Server",
    4613: "Scene Client",
    4614: "Scheduler Server",
    4615: "Scheduler Setup Server",
    4616: "Scheduler Client",
    4864: "Light Lightness Server",
    4865: "Light Lightness Setup Server",
    4866: "Light Lightness Client",
    4867: "Light CTL Server",
    4868: "Light CTL Setup Server",
    4869: "Light CTL Client",
    4870: "Light CTL Temperature Server",
    4871: "Light HSL Server",
    4872: "Light HSL Setup Server",
    4873: "Light HSL Client",
    4874: "Light HSL Hue Server",
    4875: "Light HSL Saturation Server",
    4876: "Light xyL Server",
    4877: "Light xyL Setup Server",
    4878: "Light xyL Client",
    4879: "Light LC Server",
    4880: "Light LC Setup Server",
    4881: "Light LC Client",
}
